// Bundles src/boot/runtime.ts into one minified IIFE and stores it as a string
// constant in src/boot/source.generated.ts, which src/boot.ts exports.
import { build } from "esbuild";
import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));

const result = await build({
  absWorkingDir: root,
  entryPoints: ["src/boot/runtime.ts"],
  bundle: true,
  minify: true,
  format: "iife",
  target: "es2018",
  legalComments: "none",
  write: false,
});

const code = result.outputFiles[0].text.trim();
const placeholders = code.split("__FRAMEBUDGET_OPTIONS__").length - 1;
if (placeholders !== 1) throw new Error(`Boot script must contain the options placeholder once, found ${placeholders}`);

await writeFile(
  new URL("../src/boot/source.generated.ts", import.meta.url),
  `// Generated by scripts/build-boot.mjs from src/boot/runtime.ts. Do not edit.\nexport const BOOT_SOURCE = ${JSON.stringify(code)};\n`,
);
console.log(`boot script: ${code.length} bytes minified`);
